theme = "basics"
baseURL = "http://example.org/"
languageCode = "en-us"
title = "JY L"

[params]
    author = "Jiayi"
    github = "jiayiliujiayi"
    
[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/rstudio/blogdown"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/rstudio"